<?php

namespace AppBundle\Repository;

/**
 * ArticolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticolRepository extends \Doctrine\ORM\EntityRepository
{
}
